package sop_corba.ControladorCompraIntPackage;


/**
* sop_corba/ControladorCompraIntPackage/CompraDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* lunes 1 de agosto de 2022 07:36:23 PM COT
*/

public final class CompraDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int idUsuario = (int)0;
  public String tipoIdentificacion = null;
  public double valorCompra = (double)0;
  public String lugarCompra = null;
  public String fechaCompra = null;
  public String medioPago = null;
  public String nitEmpresa = null;

  public CompraDTO ()
  {
  } // ctor

  public CompraDTO (int _idUsuario, String _tipoIdentificacion, double _valorCompra, String _lugarCompra, String _fechaCompra, String _medioPago, String _nitEmpresa)
  {
    idUsuario = _idUsuario;
    tipoIdentificacion = _tipoIdentificacion;
    valorCompra = _valorCompra;
    lugarCompra = _lugarCompra;
    fechaCompra = _fechaCompra;
    medioPago = _medioPago;
    nitEmpresa = _nitEmpresa;
  } // ctor

} // class CompraDTO
