package sop_corba.ControladorCompraIntPackage;


/**
* sop_corba/ControladorCompraIntPackage/ListCompraHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* lunes 1 de agosto de 2022 07:36:23 PM COT
*/

public final class ListCompraHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.ControladorCompraIntPackage.CompraDTO value[] = null;

  public ListCompraHolder ()
  {
  }

  public ListCompraHolder (sop_corba.ControladorCompraIntPackage.CompraDTO[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.ControladorCompraIntPackage.ListCompraHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.ControladorCompraIntPackage.ListCompraHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.ControladorCompraIntPackage.ListCompraHelper.type ();
  }

}
