package sop_corba;


/**
* sop_corba/ControladorCompraIntHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* lunes 1 de agosto de 2022 07:36:23 PM COT
*/

abstract public class ControladorCompraIntHelper
{
  private static String  _id = "IDL:sop_corba/ControladorCompraInt:1.0";

  public static void insert (org.omg.CORBA.Any a, sop_corba.ControladorCompraInt that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static sop_corba.ControladorCompraInt extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (sop_corba.ControladorCompraIntHelper.id (), "ControladorCompraInt");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static sop_corba.ControladorCompraInt read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ControladorCompraIntStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, sop_corba.ControladorCompraInt value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static sop_corba.ControladorCompraInt narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof sop_corba.ControladorCompraInt)
      return (sop_corba.ControladorCompraInt)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      sop_corba._ControladorCompraIntStub stub = new sop_corba._ControladorCompraIntStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static sop_corba.ControladorCompraInt unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof sop_corba.ControladorCompraInt)
      return (sop_corba.ControladorCompraInt)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      sop_corba._ControladorCompraIntStub stub = new sop_corba._ControladorCompraIntStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
