package sop_corba;


/**
* sop_corba/ControladorCompraIntPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* lunes 1 de agosto de 2022 07:36:23 PM COT
*/

public abstract class ControladorCompraIntPOA extends org.omg.PortableServer.Servant
 implements sop_corba.ControladorCompraIntOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("registrarCompra", new java.lang.Integer (0));
    _methods.put ("listarCanciones", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // sop_corba/ControladorCompraInt/registrarCompra
       {
         sop_corba.ControladorCompraIntPackage.CompraDTO objCompra = sop_corba.ControladorCompraIntPackage.CompraDTOHelper.read (in);
         boolean $result = false;
         $result = this.registrarCompra (objCompra);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // sop_corba/ControladorCompraInt/listarCanciones
       {
         sop_corba.ControladorCompraIntPackage.CompraDTO $result[] = null;
         $result = this.listarCanciones ();
         out = $rh.createReply();
         sop_corba.ControladorCompraIntPackage.ListCompraHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/ControladorCompraInt:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ControladorCompraInt _this() 
  {
    return ControladorCompraIntHelper.narrow(
    super._this_object());
  }

  public ControladorCompraInt _this(org.omg.CORBA.ORB orb) 
  {
    return ControladorCompraIntHelper.narrow(
    super._this_object(orb));
  }


} // class ControladorCompraIntPOA
