package sop_corba;


/**
* sop_corba/ControladorCompraInt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* lunes 1 de agosto de 2022 07:36:23 PM COT
*/

public interface ControladorCompraInt extends ControladorCompraIntOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ControladorCompraInt
