package sop_corba;


/**
* sop_corba/ControladorCompraIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* lunes 1 de agosto de 2022 07:36:23 PM COT
*/

public interface ControladorCompraIntOperations 
{
  boolean registrarCompra (sop_corba.ControladorCompraIntPackage.CompraDTO objCompra);
  sop_corba.ControladorCompraIntPackage.CompraDTO[] listarCanciones ();
} // interface ControladorCompraIntOperations
